
MACRO_COMPONENT(Name);
MACRO_COMPONENT(GraphNode);
MACRO_COMPONENT(Transform);
MACRO_COMPONENT(SpriteRenderer);
MACRO_COMPONENT(Camera);
MACRO_COMPONENT(ParticleSystem);
MACRO_COMPONENT(AABBCollider);
MACRO_COMPONENT(AudioEmitter);
MACRO_COMPONENT(PrefabInstance);
